spring:

  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  jpa:
    database: mysql

    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

decorator:
  datasource:
    p6spy:
      enable-logging: true

auth:
  jwt:
    header: ${HEADER}
    secret: ${SECRET}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
    prefix: ${PREFIXES}

bsm:
  client-id: ${BSM_CLIENT_ID}
  secret-key: ${BSM_SECRET_KEY}
  redirect-url: ${BSM_REDIRECT_URL}

image:
  path: ${SAVING_URL}

#S3
aws:
  s3:
    bucket: ${S3_BUCKET}
    access-key: ${S3_ACCESSKEY}
    secret-key: ${S3_SECRET}
    region: ${S3_REGION}
    end-point-url: ${S3_ENDPOINT_URL}
    read-url: ${S3_READ_URL}

server:
  port: 8080