spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 15
      connection-timeout: 5000
      validation-timeout: 2000
      minimum-idle: 15
      idle-timeout: 600000
      max-lifetime: 1800000

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: ${SECRET}
  accessExp: ${ACCESS_EXP}
  refreshExp: ${REFRESH_EXP}

bsm:
  client-id: ${BSM_CLIENT_ID}
  secret-key: ${BSM_SECRET_KEY}
  redirect-url: ${BSM_REDIRECT_URL}

#S3
aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
    end-point-url: ${S3_ENDPOINT_URL}
    read-url: ${S3_READ_URL}
    access-key: ${S3_ACCESSKEY}
    secret-key: ${S3_SECRET}

server:
  port: 8080